[build-system]
requires = ["setuptools>=80.9.0", "wheel"]

[project]
name = "ir-test-task"
version = "0.1.0"
description = "Test task for Internet Revolution company"
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [ { name = "Egor", email = "lotus9200@gmail.com" } ]
dependencies = [
    "aiofiles==24.1.0",
    "aiogram==3.22.0",
    "aiohappyeyeballs==2.6.1",
    "aiohttp==3.12.15",
    "aiosignal==1.4.0",
    "annotated-types==0.7.0",
    "attrs==25.4.0",
    "certifi==2025.11.12",
    "et_xmlfile==2.0.0",
    "frozenlist==1.8.0",
    "idna==3.11",
    "magic-filter==1.0.12",
    "multidict==6.7.0",
    "numpy==2.3.5",
    "openpyxl==3.1.5",
    "pandas==2.3.3",
    "propcache==0.4.1",
    "pydantic==2.11.10",
    "pydantic_core==2.33.2",
    "python-dateutil==2.9.0.post0",
    "pytz==2025.2",
    "six==1.17.0",
    "typing-inspection==0.4.2",
    "typing_extensions==4.15.0",
    "tzdata==2025.2",
    "yarl==1.22.0"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
package-dir = { "" = "src" }

[project.scripts]
run_app = "bin.bot.main:main"